# Dependencies 
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Mark Perry"
tagline:          "Development Blog"
description:      "Just one dev's thoughts on mondern developement"
url:              http://blog.markperry.co.uk
baseurl:          /

author:
  name:           'Mark Perry'
  url:            https://twitter.com/markjperry

paginate:         5

# Custom vars
github:
  repo:           https://github.com/markjperry
